### ISSUE TITLE
Ensure inheritance and dependencies invalidation is properly supported

### ISSUE THREAD

**Issue by mabar** [orisai/object-mapper#37]
- [x] annotations/attributes should define source class, if it is a parent and not the current class (prerequirement of #35)
- [x] each mapped object metadata should define list of dependencies to check for metadata invalidation (any classes used in rules, used traits, implemented interfaces and extended classes) - continues in #47 
- [x] 	referenced constants from other classes should ideally result in checking their class, but that may be not possible) - same as previous, #47 
- [x] 	cache in variable for performance in development mode (in production metadata are cached permanently) (already works partially, continues in #48)
- [x] each (mapped object) class and trait in hierarchy should allow mapped properties
- [x] each (mapped object) class and trait in hierarchy should allow callbacks - continues in #52
- [x] each (mapped object) class in hierarchy should allow docs annotations (traits probably not, some doc annotations are unique, some are not) - same as previous, #52

**Comment by mabar** [comment]
- [x] Rules, callbacks, docs and modifiers should also check scope in which are defined - while attributes and annotations validate if they are above class/property, custom sources should not be expected to do so - continues in #53
- [x] ~Traits may define Skipped and FieldName modifiers, modifier CreateWithoutConstructor should be exclusive to real class~ - BS
- [x] CreateWithoutConstructor should be allowed only by first inheritor of MappedObject, child of a mapped object implementation should not be allowed to change something, what parent class does not support - continues in #54, bit modified
- [x] ~Interfaces should not define anyting~ - it is fine, interfaces can define e.g. callbacks and docs

**Comment by mabar** [comment]
New issues opened for individual tasks (links added to relevant tasks)
