### ISSUE TITLE
Above-class meta (callbacks, modifiers) support in traits and interfaces

### ISSUE THREAD

**Issue by mabar** [orisai/object-mapper#52]
Ensure meta are loaded if defined above traits and interfaces

- [x] Above trait meta (solved by #59)
- [x] Above interface meta (solved by #58)
- [x] Before/After callbacks (solved by #58, #59)
- [x] CreateWithoutConstructor modifier (continues in #54)
