### ISSUE TITLE
Meta targets - class, property, method, ...

### ISSUE THREAD

**Issue by mabar** [orisai/object-mapper#53]
Validate if each of them is defined above valid target

- [x] Rules - only above property
- [ ] Callbacks - above class or property (all of them)
- [ ] Modifiers - above class or property (each individually)
- [ ] Docs - above class or property (each individually)

While annotations and attributes validate their targets, we should have an independent way, because:

- each annotation/attribute has to set target individually
- possible other meta sources do not have such option

**Comment by mabar** [comment]
Annotations/attributes have DefinitionTester for tests
